[tool.poetry]
name = "paste-poetry"
version = "0.1.0"
description = ""
authors = ["lavingham <egor.lavysh@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.116.1"
uvicorn = "^0.35.0"
pydantic-settings = "^2.10.1"
motor = "^3.7.1"
beanie = "^2.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
